<a href="https://colab.research.google.com/github/nicas83/ispr22/blob/main/GNicassio_Assignment1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install hmmlearn

# Assignment 1

Fit an Hidden Markov Model with Gaussian emissions to the data in DSET1: it is sufficient to focus on the “Appliances” and “Lights” columns of the dataset which measure the energy consumption of appliances and lights, respectively, across a period of 4.5 months. Consider the two columns in isolation, i.e. train two separate HMM, one for appliances and one for light.  Experiment with HMMs with a varying number of hidden states (e.g. at least 2, 3 and 4). Once trained the HMMs, perform Viterbi on a reasonably sized subsequence (e.g. 1 month of data) and plot the timeseries data highlighting (e.g. with different colours) the hidden state assigned to each timepoint by the Viterbi algorithm.  Then, fit a single HMM emitting both appliance and light with the same model and repeat the Viterbi assessment. Confront the two results.

In [24]:
import matplotlib.pyplot as plot
import pandas as pd
import numpy as np
from hmmlearn import hmm
from sklearn.model_selection import train_test_split

In [56]:
data = pd.read_csv('/content/energydata_complete.csv')
# convert string date into dateformat
data["date"] = pd.to_datetime(data["date"])

Considering the Hidden Markov Model for the Appliances with respectively 2,3 and 4 hidden states.
For each experiment is important to split the dataset into training set and validation set (80-20) to ensure that the model is fitting well (use the score() function to extract the best model).
Then make the assumption on the n_component variable that means make assumption on the states of the HMM (high, low, medium for example).
Non c'è il set di model parameters iniziale (pigreco, A e theta), quindi devo appliare l'algoritmo di EM per individuarle e ricomputare con Viterbi.

In [ ]:
# plotting the initial dataset considering only datetime and appliances
#data = data[data["date"] <= pd.to_datetime("2016-02-02 ")] 
figure, ax = plot.subplots(figsize=(15,15))
ax.plot(data["date"], data["Appliances"])
ax.autoscale(enable=True, axis="x", tight=True)
plot.show()

In [ ]:
# plotting the initial dataset considering only datetime and lights
figure, ax = plot.subplots(figsize=(15,15))
ax.plot(data["date"], data["lights"])
ax.autoscale(enable=True, axis="x", tight=True)
plot.show()

In [41]:
# split the array into training and test set
x_train, x_test = train_test_split(data, shuffle=True)
print ("Lunghezza train")
print (len(x_train))
print ("Lunghezza test")
print (len(x_test))

Lunghezza train
14801
Lunghezza test
4934


In [44]:

# build and fit an HMM on the first column "Appliances"
X_fit = x_train[['Appliances']].values
X_predict = x_test[['Appliances']].values

X_fit = np.sort(X_fit)
# hidden states= 3
model = hmm.GaussianHMM(n_components= 4, covariance_type="full", n_iter = 1000)
model.fit(X_fit)
print ("model score:") 
print (model.decode(X_fit, algorithm='viterbi'))

Z = model.predict(X_predict)
states = pd.unique(Z)

print ("Printing states:")
print (states)

print ("Start probability")
print (model.startprob_)

print ("Transition Matrix")
print (model.transmat_)

print ("Gaussian distribution means:")
print (model.means_)

print("\nGaussian distribution covariances:")
print(model.covars_)

/usr/local/lib/python3.9/dist-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 10 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(


model score:
(-79192.19103207394, array([3, 2, 1, ..., 1, 1, 3]))
Printing states:
[3 1 0 2]
Start probability
[1.41867298e-274 2.59015983e-285 0.00000000e+000 1.00000000e+000]
Transition Matrix
[[4.68018335e-01 6.61055295e-03 1.67550321e-02 5.08616080e-01]
 [1.82345462e-01 4.01956842e-01 1.37813461e-01 2.77884235e-01]
 [1.91062344e-01 4.22890510e-01 1.15251153e-01 2.70795992e-01]
 [5.17314028e-07 7.07934115e-01 2.07430349e-01 8.46350192e-02]]
Gaussian distribution means:
[[ 51.34446845]
 [ 82.77850001]
 [306.23675124]
 [ 51.24739439]]

Gaussian distribution covariances:
[[[  111.90334888]]

 [[  905.46203689]]

 [[25422.62596305]]

 [[  102.17625067]]]
